# Generated by Django 4.2.5 on 2023-09-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppOlivera", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=40)),
                ("apellido", models.CharField(max_length=40)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Lugar_Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=40)),
                ("localidad", models.CharField(max_length=40)),
                ("email", models.EmailField(max_length=254)),
                ("salon", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="Tipo_Servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=40)),
                ("evento", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="Trabajos_entregar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=40)),
                ("fecha_entrega", models.DateField()),
                ("entregado", models.BooleanField()),
                ("link", models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.DeleteModel(name="Curso",),
    ]
