# Generated by Django 4.2.5 on 2023-09-11 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "AppOlivera",
            "0002_cliente_lugar_evento_tipo_servicio_trabajos_entregar_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="trabajos_entregar",
            name="trabajo_cliente",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="AppOlivera.cliente",
            ),
            preserve_default=False,
        ),
    ]
