# Generated by Django 4.2.5 on 2023-09-12 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("AppOlivera", "0006_remove_trabajos_entregar_trabajo_cliente"),
    ]

    operations = [
        migrations.AddField(
            model_name="trabajos_entregar",
            name="trabajo_cliente",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="AppOlivera.cliente",
            ),
            preserve_default=False,
        ),
    ]
