# Generated by Django 4.2.5 on 2023-09-12 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppOlivera", "0007_trabajos_entregar_trabajo_cliente"),
    ]

    operations = [
        migrations.RemoveField(model_name="trabajos_entregar", name="trabajo_cliente",),
    ]
